use crate::syntax::json_parser::JsonValue;

// Generated by build.rs — embeds languages.json and grammar files
include!(concat!(env!("OUT_DIR"), "/embedded_grammars.rs"));

// ── Language definition ─────────────────────────────────────

pub struct LanguageDef {
    pub name: String,
    pub extensions: Vec<String>,
    pub grammar_file: String,
    pub comment: Option<String>,
}

pub fn builtin_languages() -> Vec<LanguageDef> {
    parse_languages_array(EMBEDDED_LANGUAGES_JSON).unwrap_or_default()
}

/// Parse a JSON array of language definitions (used for both embedded and config).
fn parse_languages_array(json_str: &str) -> Option<Vec<LanguageDef>> {
    let val = JsonValue::parse(json_str).ok()?;
    let arr = val.as_array()?;
    let mut langs = Vec::new();
    for item in arr {
        let name = item.get("name")?.as_str()?.to_string();
        let extensions: Vec<String> = item
            .get("extensions")?
            .as_array()?
            .iter()
            .filter_map(|v| v.as_str().map(|s| s.to_string()))
            .collect();
        let grammar_file = item.get("grammar")?.as_str()?.to_string();
        if name.is_empty() || extensions.is_empty() || grammar_file.is_empty() {
            continue;
        }
        let comment = item
            .get("comment")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string());
        langs.push(LanguageDef {
            name,
            extensions,
            grammar_file,
            comment,
        });
    }
    Some(langs)
}

/// Parse languages from a config.json object (has "languages" key wrapping an array).
fn parse_languages_from_config(val: &JsonValue) -> Option<Vec<LanguageDef>> {
    let arr = val.get("languages")?.as_array()?;
    let mut langs = Vec::new();
    for item in arr {
        let name = item.get("name")?.as_str()?.to_string();
        let extensions: Vec<String> = item
            .get("extensions")?
            .as_array()?
            .iter()
            .filter_map(|v| v.as_str().map(|s| s.to_string()))
            .collect();
        let grammar_file = item.get("grammar")?.as_str()?.to_string();
        if name.is_empty() || extensions.is_empty() || grammar_file.is_empty() {
            continue;
        }
        let comment = item
            .get("comment")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string());
        langs.push(LanguageDef {
            name,
            extensions,
            grammar_file,
            comment,
        });
    }
    Some(langs)
}

fn merge_languages(user: Vec<LanguageDef>, mut builtins: Vec<LanguageDef>) -> Vec<LanguageDef> {
    let mut result: Vec<LanguageDef> = Vec::new();
    // User entries override built-ins by name
    for entry in user {
        // Remove any matching built-in
        builtins.retain(|b| b.name != entry.name);
        result.push(entry);
    }
    // Append remaining built-ins
    result.extend(builtins);
    result
}

// ── Config ──────────────────────────────────────────────────

pub struct Config {
    pub tab_size: usize,
    pub use_spaces: bool,
    pub theme: String,
    pub line_numbers: bool,
    pub auto_indent: bool,
    pub word_wrap: bool,
    pub languages: Vec<LanguageDef>,
    pub filetree_width: u16,
    pub filetree_ignored: Vec<String>,
    pub terminal_shell: String,
    pub terminal_scrollback: usize,
    pub keybindings: crate::keybindings::KeyMap,
    pub lsp_servers: Vec<(String, crate::lsp::LspServerConfig)>,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            tab_size: 4,
            use_spaces: true,
            theme: "zedit-dark".to_string(),
            line_numbers: true,
            auto_indent: true,
            word_wrap: false,
            languages: builtin_languages(),
            filetree_width: 30,
            filetree_ignored: Vec::new(),
            terminal_shell: String::new(),
            terminal_scrollback: 1000,
            keybindings: crate::keybindings::KeyMap::defaults(),
            lsp_servers: Vec::new(),
        }
    }
}

impl Config {
    pub fn load() -> Self {
        let home = match std::env::var("HOME") {
            Ok(h) => h,
            Err(_) => return Config::default(),
        };

        let mut config = Config::default();

        // Merge auto-discovered grammars from ~/.config/zedit/grammars/
        let discovered = crate::syntax::highlight::discover_user_grammars(&home);
        if !discovered.is_empty() {
            config.languages = merge_languages(discovered, config.languages);
        }

        // Load and apply config.json
        let path = format!("{}/.config/zedit/config.json", home);
        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(e) => {
                crate::dlog!("[config] cannot read {}: {}", path, e);
                return config;
            }
        };
        crate::dlog!("[config] loaded {} bytes from {}", content.len(), path);
        let val = match JsonValue::parse(&content) {
            Ok(v) => v,
            Err(e) => {
                crate::dlog!("[config] JSON parse error: {:?} — LSP will NOT load", e);
                return config;
            }
        };
        crate::dlog!("[config] JSON parsed OK");
        if let Some(n) = val.get("tab_size").and_then(|v| v.as_f64()) {
            config.tab_size = (n as usize).clamp(1, 16);
        }
        if let Some(b) = val.get("use_spaces").and_then(|v| v.as_bool()) {
            config.use_spaces = b;
        }
        if let Some(s) = val.get("theme").and_then(|v| v.as_str()) {
            config.theme = s.to_string();
        }
        if let Some(b) = val.get("line_numbers").and_then(|v| v.as_bool()) {
            config.line_numbers = b;
        }
        if let Some(b) = val.get("auto_indent").and_then(|v| v.as_bool()) {
            config.auto_indent = b;
        }
        if let Some(b) = val.get("word_wrap").and_then(|v| v.as_bool()) {
            config.word_wrap = b;
        }
        if let Some(n) = val.get("filetree_width").and_then(|v| v.as_f64()) {
            config.filetree_width = (n as u16).clamp(15, 60);
        }
        if let Some(arr) = val.get("filetree_ignored").and_then(|v| v.as_array()) {
            config.filetree_ignored = arr
                .iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect();
        }
        if let Some(s) = val.get("terminal_shell").and_then(|v| v.as_str()) {
            config.terminal_shell = s.to_string();
        }
        if let Some(n) = val.get("terminal_scrollback").and_then(|v| v.as_f64()) {
            config.terminal_scrollback = (n as usize).clamp(100, 100_000);
        }
        // Keybinding overrides
        let keybindings_val = val.get("keybindings");
        config.keybindings = crate::keybindings::KeyMap::new(keybindings_val);

        // LSP server configuration
        if let Some(lsp_obj) = val.get("lsp").and_then(|v| v.as_object()) {
            crate::dlog!("[config] found lsp section with {} entries", lsp_obj.len());
            for (lang, server_val) in lsp_obj {
                if let Some(command) = server_val.get("command").and_then(|v| v.as_str()) {
                    let args = server_val
                        .get("args")
                        .and_then(|v| v.as_array())
                        .map(|arr| {
                            arr.iter()
                                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                                .collect()
                        })
                        .unwrap_or_default();
                    crate::dlog!("[config] lsp server: lang={} command={}", lang, command);
                    config.lsp_servers.push((
                        lang.clone(),
                        crate::lsp::LspServerConfig {
                            command: command.to_string(),
                            args,
                        },
                    ));
                }
            }
        }

        // config.json overrides take highest priority
        if let Some(user_langs) = parse_languages_from_config(&val) {
            config.languages = merge_languages(user_langs, config.languages);
        }
        config
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_defaults() {
        let config = Config::default();
        assert_eq!(config.tab_size, 4);
        assert_eq!(config.theme, "zedit-dark");
        assert!(config.line_numbers);
        assert!(config.auto_indent);
    }

    #[test]
    fn test_default_languages_not_empty() {
        let config = Config::default();
        assert!(!config.languages.is_empty());
    }

    #[test]
    fn test_builtin_languages_parsed_from_json() {
        let langs = builtin_languages();
        assert!(!langs.is_empty());
        let rust = langs.iter().find(|l| l.name == "rust").unwrap();
        assert_eq!(rust.extensions, vec!["rs"]);
        assert_eq!(rust.grammar_file, "rust.tmLanguage.json");
        assert_eq!(rust.comment.as_deref(), Some("//"));
        let md = langs.iter().find(|l| l.name == "markdown").unwrap();
        assert!(md.comment.is_none());
    }

    #[test]
    fn test_parse_partial() {
        let json = r#"{"tab_size": 2, "line_numbers": false}"#;
        let val = JsonValue::parse(json).unwrap();
        let mut config = Config::default();
        if let Some(n) = val.get("tab_size").and_then(|v| v.as_f64()) {
            config.tab_size = (n as usize).clamp(1, 16);
        }
        if let Some(b) = val.get("line_numbers").and_then(|v| v.as_bool()) {
            config.line_numbers = b;
        }
        assert_eq!(config.tab_size, 2);
        assert!(!config.line_numbers);
        assert_eq!(config.theme, "zedit-dark");
        assert!(config.auto_indent);
    }

    #[test]
    fn test_clamp_tab_size() {
        let json = r#"{"tab_size": 100}"#;
        let val = JsonValue::parse(json).unwrap();
        let n = val.get("tab_size").and_then(|v| v.as_f64()).unwrap();
        let clamped = (n as usize).clamp(1, 16);
        assert_eq!(clamped, 16);

        let json = r#"{"tab_size": 0}"#;
        let val = JsonValue::parse(json).unwrap();
        let n = val.get("tab_size").and_then(|v| v.as_f64()).unwrap();
        let clamped = (n as usize).clamp(1, 16);
        assert_eq!(clamped, 1);
    }

    #[test]
    fn test_invalid_json_returns_defaults() {
        let config = Config::default();
        assert_eq!(config.tab_size, 4);
        assert!(config.line_numbers);
    }

    #[test]
    fn test_user_override_replaces_builtin() {
        let json = r#"{"languages": [{"name": "rust", "extensions": ["rs", "rsx"], "grammar": "rust.tmLanguage.json", "comment": "//"}]}"#;
        let val = JsonValue::parse(json).unwrap();
        let user_langs = parse_languages_from_config(&val).unwrap();
        let merged = merge_languages(user_langs, builtin_languages());
        let rust = merged.iter().find(|l| l.name == "rust").unwrap();
        assert_eq!(rust.extensions, vec!["rs", "rsx"]);
        // Other built-ins still present
        assert!(merged.iter().any(|l| l.name == "python"));
        assert_eq!(merged.len(), builtin_languages().len()); // replaced, not duplicated
    }

    #[test]
    fn test_user_adds_new_language() {
        let json = r##"{"languages": [{"name": "ruby", "extensions": ["rb", "rake"], "grammar": "ruby.tmLanguage.json", "comment": "#"}]}"##;
        let val = JsonValue::parse(json).unwrap();
        let user_langs = parse_languages_from_config(&val).unwrap();
        let merged = merge_languages(user_langs, builtin_languages());
        assert!(merged.iter().any(|l| l.name == "ruby"));
        assert_eq!(merged.len(), builtin_languages().len() + 1); // built-ins + 1 new
    }

    #[test]
    fn test_no_languages_key_uses_builtins() {
        let json = r#"{"tab_size": 2}"#;
        let val = JsonValue::parse(json).unwrap();
        assert!(parse_languages_from_config(&val).is_none());
    }
}
